// app/api/prodi/route.js
import clientPromise from "@/lib/mongodb";
import { ObjectId } from "mongodb";
import { v2 as cloudinary } from "cloudinary";
import dbConnect from '@/lib/mongoose';
import Prodi from '@/models/Prodi';

// Konfigurasi Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const uploadToCloudinary = (buffer, options = {}) =>
  new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(options, (error, result) => {
      if (error) reject(error);
      else resolve(result);
    });
    stream.end(buffer);
  });

// GET semua prodi
export async function GET() {
  // Prefer Mongoose for reads (works for both string _id and ObjectId docs), fallback to native driver
  try {
    await dbConnect();
    const docs = await Prodi.find({}).lean().sort({ updatedAt: -1 });
    // map new field names to legacy response keys so frontend continues to work
    const mapped = docs.map((d) => ({
      ...d,
      dokumenUrl_akreditasi: d.dokumenAkreditasi || null,
      dokumenName_akreditasi: d.dokumenName_akreditasi || null,
    }));
    return new Response(JSON.stringify(mapped), { status: 200 });
  } catch (err) {
    const client = await clientPromise;
    const db = client.db("websitefkom");
    const prodi = await db.collection("prodi").find({}).toArray();
    return new Response(JSON.stringify(prodi), { status: 200 });
  }
}

// POST tambah prodi
export async function POST(req) {
  try {
    const formData = await req.formData();
    const nama = formData.get("nama");
    const deskripsi = formData.get("deskripsi");
    const visi = formData.get("visi") || "";
    const misi = formData.getAll("misi").filter(Boolean);
    const akreditasi = formData.get("akreditasi") || "";
    const tahun_akreditasi = formData.get("tahun_akreditasi") || "";

    const gambarFile = formData.get("gambar");
    const dokumenFile = formData.get("dokumen"); // PDF

    let gambarUrl = null;
    let dokumenUrl = null;
    let dokumenName = null;

    // Upload gambar jika ada (default resource_type = image)
    if (gambarFile && typeof gambarFile.arrayBuffer === "function") {
      const bytes = await gambarFile.arrayBuffer();
      const buffer = Buffer.from(bytes);
      const imgRes = await uploadToCloudinary(buffer, { folder: "prodi/images" });
      gambarUrl = imgRes.secure_url;
    }

    // Upload dokumen (PDF) jika ada (resource_type = 'raw')
    if (dokumenFile && typeof dokumenFile.arrayBuffer === "function") {
      const bytes = await dokumenFile.arrayBuffer();
      const buffer = Buffer.from(bytes);
      const docRes = await uploadToCloudinary(buffer, {
        folder: "prodi/akreditasi",
        resource_type: "raw",
      });
      dokumenUrl = docRes.secure_url;
      // gunakan nama file asli dari client sebagai dokumenName
      dokumenName = dokumenFile.name || docRes.original_filename || "";
    }

    // Use Mongoose model so pre-save hook generates custom _id and optional thumbnail
    await dbConnect();

    const prodi = new Prodi({
      nama,
      deskripsi,
      gambar: gambarUrl,
      visi,
      misi,
      akreditasi,
      tahun_akreditasi,
      dokumenAkreditasi: dokumenUrl,
      // keep legacy name in mongoose document for backward compatibility if needed
      dokumenName_akreditasi: dokumenName || null,
      // thumbnailAkreditasi will be generated by model pre-save when possible
    });

    const saved = await prodi.save();
    // convert to plain object and attach legacy response fields
    const obj = saved.toObject({ getters: true, versionKey: false });
    obj.dokumenUrl_akreditasi = obj.dokumenAkreditasi || null;
    obj.dokumenName_akreditasi = obj.dokumenName_akreditasi || dokumenName || null;
    return new Response(JSON.stringify(obj), { status: 201 });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}

// DELETE prodi
export async function DELETE(req) {
  try {
    const { id } = await req.json();
    // Try to delete by string _id (new Prodi docs) using Mongoose first
    await dbConnect();
    const byModel = await Prodi.findById(id);
    if (byModel) {
      await Prodi.deleteOne({ _id: id });
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    // Fallback: assume legacy ObjectId
    const client = await clientPromise;
    const db = client.db("websitefkom");
    await db.collection("prodi").deleteOne({ _id: new ObjectId(id) });
    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}

// PUT update prodi
export async function PUT(req) {
  try {
    const formData = await req.formData();
    const id = formData.get("id");
    if (!id) return new Response(JSON.stringify({ error: "Missing id" }), { status: 400 });

    const nama = formData.get("nama");
    const deskripsi = formData.get("deskripsi");
    const visi = formData.get("visi") || "";
    const misi = formData.getAll("misi").filter(Boolean);
    const akreditasi = formData.get("akreditasi") || "";
    const tahun_akreditasi = formData.get("tahun_akreditasi") || "";

    const gambarFile = formData.get("gambar");
    const dokumenFile = formData.get("dokumen"); // PDF (opsional)

    const updateData = {
      nama,
      deskripsi,
      visi,
      misi,
      akreditasi,
      tahun_akreditasi,
      updatedAt: new Date(),
    };

    // Upload gambar jika ada
    if (gambarFile && typeof gambarFile.arrayBuffer === "function") {
      const bytes = await gambarFile.arrayBuffer();
      const buffer = Buffer.from(bytes);
      const imgRes = await uploadToCloudinary(buffer, { folder: "prodi/images" });
      updateData.gambar = imgRes.secure_url;
    }

    // Upload dokumen PDF jika ada -> hanya menimpa bila ada file baru
    if (dokumenFile && typeof dokumenFile.arrayBuffer === "function") {
      const bytes = await dokumenFile.arrayBuffer();
      const buffer = Buffer.from(bytes);
      const docRes = await uploadToCloudinary(buffer, {
        folder: "prodi/akreditasi",
        resource_type: "raw",
      });
      updateData.dokumenUrl_akreditasi = docRes.secure_url;
      updateData.dokumenName_akreditasi = dokumenFile.name || docRes.original_filename || "";
    }

    // Try to update using Mongoose for docs that use string custom _id
    await dbConnect();
    const byModel = await Prodi.findById(id);
    if (byModel) {
      // apply only fields provided (to avoid overwriting with undefined)
      if (nama) byModel.nama = nama;
      if (deskripsi) byModel.deskripsi = deskripsi;
      byModel.visi = visi;
      if (Array.isArray(misi) && misi.length) byModel.misi = misi;
      byModel.akreditasi = akreditasi;
      byModel.tahun_akreditasi = tahun_akreditasi;
      // handle uploads
      if (updateData.gambar) byModel.gambar = updateData.gambar;
      if (updateData.dokumenUrl_akreditasi) {
        byModel.dokumenAkreditasi = updateData.dokumenUrl_akreditasi;
        byModel.dokumenName_akreditasi = updateData.dokumenName_akreditasi || byModel.dokumenName_akreditasi || null;
      }

      byModel.updatedAt = new Date();
      const saved = await byModel.save();
      const obj = saved.toObject({ getters: true, versionKey: false });
      obj.dokumenUrl_akreditasi = obj.dokumenAkreditasi || null;
      obj.dokumenName_akreditasi = obj.dokumenName_akreditasi || null;
      return new Response(JSON.stringify(obj), { status: 200 });
    }

    // Fallback for legacy ObjectId documents
    const client = await clientPromise;
    const db = client.db("websitefkom");

    await db.collection("prodi").updateOne(
      { _id: new ObjectId(id) },
      { $set: updateData }
    );

    const updatedDoc = await db.collection("prodi").findOne({ _id: new ObjectId(id) });

    return new Response(JSON.stringify(updatedDoc), { status: 200 });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}
